---
#with_items concept in ansible to install

- hosts: all
  become: true
  tasks:
  - name: Install packages
    apt: 
      name: "{{ item }}"
      update_cache: yes
    with_items:
        - vim
        - zip
        - tree
        - curl
        - wget
